openapi: 3.1.0
info:
  title: Market Intel GPT API
  version: 1.0.0
  description: Aggregated real-time market data for BTC/USDT, DXY, and news events from TAAPI.io, Twelve Data, and NewsData.io.

servers:
  - url: https://api.taapi.io
    description: TAAPI.io for technical indicators
  - url: https://api.twelvedata.com
    description: Twelve Data for DXY index
  - url: https://newsdata.io/api/1
    description: NewsData.io for economic news

paths:
  /atr:
    get:
      operationId: getAtr
      summary: Get ATR for BTC/USDT (5m)
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
        - name: exchange
          in: query
          required: true
          example: binance
          schema:
            type: string
        - name: symbol
          in: query
          required: true
          example: BTC/USDT
          schema:
            type: string
        - name: interval
          in: query
          required: true
          example: 5m
          schema:
            type: string
      responses:
        '200':
          description: ATR value
          content:
            application/json:
              schema:
                type: object

  /macd:
    get:
      operationId: getMacd
      summary: Get MACD for BTC/USDT (5m)
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
        - name: exchange
          in: query
          required: true
          example: binance
          schema:
            type: string
        - name: symbol
          in: query
          required: true
          example: BTC/USDT
          schema:
            type: string
        - name: interval
          in: query
          required: true
          example: 5m
          schema:
            type: string
      responses:
        '200':
          description: MACD data
          content:
            application/json:
              schema:
                type: object

  /obv:
    get:
      operationId: getObv
      summary: Get OBV for BTC/USDT (5m)
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
        - name: exchange
          in: query
          required: true
          example: binance
          schema:
            type: string
        - name: symbol
          in: query
          required: true
          example: BTC/USDT
          schema:
            type: string
        - name: interval
          in: query
          required: true
          example: 5m
          schema:
            type: string
      responses:
        '200':
          description: OBV value
          content:
            application/json:
              schema:
                type: object

  /mfi:
    get:
      operationId: getMfi
      summary: Get MFI for BTC/USDT (5m)
      parameters:
        - name: secret
          in: query
          required: true
          schema:
            type: string
        - name: exchange
          in: query
          required: true
          example: binance
          schema:
            type: string
        - name: symbol
          in: query
          required: true
          example: BTC/USDT
          schema:
            type: string
        - name: interval
          in: query
          required: true
          example: 5m
          schema:
            type: string
      responses:
        '200':
          description: MFI value
          content:
            application/json:
              schema:
                type: object

  /price:
    get:
      operationId: getDxyPrice
      summary: Get real-time DXY price from Twelve Data
      parameters:
        - name: symbol
          in: query
          required: true
          example: DXY
          schema:
            type: string
        - name: apikey
          in: query
          required: true
          schema:
            type: string
      responses:
        '200':
          description: DXY price data
          content:
            application/json:
              schema:
                type: object

  /news:
    get:
      operationId: getRedFlagNews
      summary: Get economic red flag news headlines
      parameters:
        - name: apikey
          in: query
          required: true
          schema:
            type: string
        - name: country
          in: query
          required: false
          example: us
          schema:
            type: string
        - name: category
          in: query
          required: false
          example: business
          schema:
            type: string
        - name: language
          in: query
          required: false
          example: en
          schema:
            type: string
      responses:
        '200':
          description: News data
          content:
            application/json:
              schema:
                type: object
