openapi: 3.1.0
info:
  title: NewsData.io Economic News API
  version: 1.0.0
  description: Fetch economic and business news headlines to detect red flag events before trading.

servers:
  - url: https://newsdata.io/api/1
    description: NewsData.io API server

paths:
  /news:
    get:
      operationId: getRedFlagNews
      summary: Get latest economic or business news
      description: Retrieves recent headlines from NewsData.io to detect red flag events that may impact trading.
      parameters:
        - name: apikey
          in: query
          required: true
          schema:
            type: string
        - name: country
          in: query
          required: false
          example: us
          schema:
            type: string
        - name: category
          in: query
          required: false
          example: business
          schema:
            type: string
        - name: language
          in: query
          required: false
          example: en
          schema:
            type: string
      responses:
        '200':
          description: News response with headlines
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  results:
                    type: array
                    items:
                      type: object
                      properties:
                        title:
                          type: string
                        description:
                          type: string
                        link:
                          type: string
                        pubDate:
                          type: string
